### PR TITLE
Changed the filename to make it work with latest OCM.

### PR DESCRIPTION
**Pull request by JacobHin2**
image

### CODE REVIEW

**Comment by KforG** [comment]
From my testing, the capitalized F did not make a difference, to the functionality of the program.

Did you experience an issue with it?

**Comment by JacobHin2** [comment]
Yes, I'll try get a screenshot of the error.
image
As long as it doesn't cause any errors, it should be fine(?)

**Comment by JacobHin2** [comment]
I mainly did this so I can say I contributed to a OSS project lol, you don't have to merge anything

I'm impressed you saw it so quick

**Comment by KforG** [comment]
Right okay, and the changed filename fixed it I assume?

**Comment by JacobHin2** [comment]
> Right okay, and the changed filename fixed it I assume?


Yes

**Comment by KforG** [comment]
> I mainly did this so I can say I contributed to a OSS project lol, you don't have to merge anything

Well congratz then I guess.

**Pull request merged**
